spring:
   application:
     name: Question-Service
   datasource:
     url: jdbc:mysql://localhost:3306/question_service
     username: root
     password: Teja@123
   jpa:
     hibernate:
       ddl-auto: update
       properties:
         hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

